### PR TITLE
Plugin interface

### PR DESCRIPTION
**Pull request by wbyoung**
This is a drastic change that I'm proposing to address #4.

I'd love to discuss it. I think it might be possible to use this idea and merge this together with _gulp-useref_ instead of putting it in here. Either way, I think this could be a good change.

Here's how you can process files with this change now:

``` javascript
gulp.task('html', resources, function() {
  var bundler = bundle();
  var jsFilter = filter('**/*.js');
  var cssFilter = filter('**/*.css');
  return gulp.src('**/*.html')
    .pipe(bundler) // after this we'll only be looking at .js and .css files
    .pipe(jsFilter)
    .pipe(uglify())
    .pipe(jsFilter.restore())
    .pipe(cssFilter)
    .pipe(minifyCss())
    .pipe(cssFilter.restore())
    .pipe(gulp.dest('dist')) // save out all .js and .css files
    .pipe(bundler.restore()) // now we're only working with the html files again
    .pipe(useref())
    .pipe(gulp.dest('dist')));
});
```

This feels more true to the ideas of how gulp is supposed to work (each task only does one thing). Actually, this is doing a little more than one thing since it's concatenating files, but I felt that made sense.

We can tweak how this works, but I'd love to know if you're open to making changes like this either in _gulp-bundle_ or _gulp-useref_. I'd prefer not to see the plugin space get any more cluttered up.

### CODE REVIEW

**Comment by wbyoung** [comment]
After thinking this over a little, I think it might make a lot more sense to add this to _gulp-useref_. It could look something like:

``` javascript
gulp.task('html', resources, function() {
  var refBuilder = useref();
  var jsFilter = filter('**/*.js');
  var cssFilter = filter('**/*.css');
  return gulp.src('**/*.html')
    .pipe(refBuilder)
    .pipe(gulp.dest('dist')) // save out html files
    .pipe(refBuilder.resources()) // after this we'll only be looking at .js and .css files
    .pipe(jsFilter)
    .pipe(uglify())
    .pipe(jsFilter.restore())
    .pipe(cssFilter)
    .pipe(minifyCss())
    .pipe(cssFilter.restore())
    .pipe(gulp.dest('dist')) // save out all .js and .css files
    .pipe(refBuilder.restore()); // if required, we can only working with the html files again
});
```

**Comment by jonkemp** [comment]
I'm still not sure what issue you are trying to solve here.

**Comment by wbyoung** [comment]
Was your comment before on ticket #3 meant to be here? Is this the one that was confusing you?

The problem I'm having was from #4, and is because I need to run _gulp-replace_ before processing some `html` files through _gulp-bundle_. My HTML looks like:

``` html
    <!-- build:js /scripts/application.js -->
    <script src="@@replaceme"></script>
    <!-- endbuild -->
```

And while I've figured out how to use both _gulp-useref_ and _gulp-bundle_, the fact that they're two modules that kind of require one another, but one isn't really a _gulp_ plugin makes them a little hard to understand at first. Also, the bundle part here is really doing a lot more than one thing which kind of breaks the ideas behind _gulp_. It solves one problem and also makes it far more _gulp-like_.

**Comment by jonkemp** [comment]
No, it was meant to be here. It would help me if you would create an issue first to discuss the problem before submitting a pull request.

You can do your gulp-replace in a separate task and make that task a prerequisite that runs before your bundle task.

I agree that it could be confusing. To address this, I was thinking of having gulp-useref call gulp-bundle from the plugin itself instead of in a separate task, since it really is a dependency. The problem with changing this now, is that these plugins are part of the Yeoman gulp webapp generator so I was waiting on feedback from the Yeoman team for this idea.

Anyway, the fact that gulp-bundle is doing more than one thing is the reason it's not a gulp plugin. It just grabs the files and passes them to other gulp plugins. Which is another reason to have gulp-useref call it directly. It would also simplify the code in gulp-bundle quite a bit.

I appreciate the pull request. I will need some time to consider it.

**Comment by jonkemp** [comment]
I noticed that you included 2 commits in this pull request, one of which is part of the other pull request which I already closed. Please remove that commit and update your pull request.

In the future, what you should do instead is just create a separate branch for each pull request to keep them separate.

**Comment by jonkemp** [comment]
I'm not really sure how your above code will work. Have you tested it? What does the filter function do? Because now you have js and css files in the same stream. So if filter is only passing one or the other, how do the other files get passed down? This is why gulp-bundle works the way it does currently by getting the files and processing them separately.

**Comment by wbyoung** [comment]
I switched it to one commit now. Sorry about that. I branched from what I was previously working on by accident. The first bit of example code actually does work and is tested (though it doesn't include any unit tests). The second bit of code is just an adaptation thinking off the first bit of code, and I think would be a better solution.

The filters are being reset (as explained in the filter plugin's documentation) and the same idea as what's being done in resetting filters can be used by this plugin or the _gulp-useref_ (depending on the example you look at from above) to switch between which set of files are being targeted later down the chain.

Doing a _gulp-replace_ in a separate task kind of defeats the purpose of steam based processing and requires temporary files. These are things that gulp is trying to avoid.

Anyone on the Yeoman team we can ping to continue discussing? That second example I gave would certainly allow full backwards compatibility if I move the code over to _gulp-useref_, is extremely configurable, and very much in line with the architecture of _gulp_.

Also, as of right now this should be fully backward compatible with your documentation.

**Comment by jonkemp** [comment]
Can you please submit a pull request for this in gulp-useref? I do think this idea may be a good solution and probably better fits there. I would probably deprecate gulp-bundle then, although I do like the name. I'll deal with the Yeoman integration. Thanks!

**Comment by wbyoung** [comment]
Closing in favor of [implementation in gulp-useref](https://github.com/jonkemp/gulp-useref/pull/3).

**Pull request closed without merging**
